version: "3"
services:
  db:
    image: cockroachdb/cockroach:v1.1.4
    ports:
    - "26257:26257"
    volumes:
    - "${PWD}/roachdata/roach1:/cockroach/cockroach-data"
    command: start --insecure

  binance:
    build: .
    image: live-ticker
    environment:
     - NODE_ENV=production
     - LT_EXCHANGE=binance
     - LT_INTERVAL=10000
    depends_on:
      - db

  kraken:
    build: .
    image: live-ticker
    environment: 
     - NODE_ENV=production
     - LT_EXCHANGE=kraken
    depends_on:
      - db
